# Generated by Django 2.1.2 on 2018-10-21 04:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('friend_id', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, unique=True), size=None)),
                ('date_added', models.TimeField()),
                ('date_modified', models.TimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contact_list',
            },
        ),
    ]
