# Generated by Django 2.1.2 on 2018-11-23 23:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('friend_id', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(unique=True), null=True, size=None)),
                ('date_added', models.DateTimeField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contact_list',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('profile_img', models.BinaryField(blank=True, null=True)),
                ('profile_description', models.TextField(blank=True, null=True)),
                ('profile_img_str', models.TextField(null=True)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
