# Generated by Django 2.1.2 on 2018-11-18 01:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='friend_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(unique=True), size=None),
        ),
    ]
