# Generated by Django 2.1.2 on 2018-11-18 02:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0002_auto_20181118_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='friend_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(unique=True), null=True, size=None),
        ),
    ]
