# Generated by Django 2.1.2 on 2018-11-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0004_auto_20181118_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
