"""
Django settings for BigChat project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import json

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
currRelPath = os.path.join(os.getcwd(), "BigChat")
filePath = os.path.join(currRelPath, "secret_key.json")
secretKey = open(filePath, "r")
jsonObj = json.load(secretKey)
SECRET_KEY = jsonObj["SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# SECURITY WARNING Make sure database credentials are secure/hidden
# For production...
filePath = os.path.join(currRelPath, "databaseCred.json")
dbCred = open(filePath, "r")
DATABASES = json.load(dbCred)

# For local database testing
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# filePath = os.path.join(currRelPath, "facebook_key.json")
# fbKey = open(filePath, "r")
# jsonObj = json.load(fbKey)
# SOCIAL_AUTH_FACEBOOK_KEY = fbKey["KEY"]
# SOCIAL_AUTH_FACEBOOK_SECRET = fbKey["SECRET"]
# SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']

# filePath = os.path.join(currRelPath, "google_key.json")
# googleKey = open(filePath, "r")
# jsonObj = json.load(googleKey)
# SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = googleKey["KEY"]
# SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = googleKey["SECRET"]


ALLOWED_HOSTS = ["*"]


# AUTHENTICATION_BACKENDS = (

#     'social_core.backends.google.GoogleOAuth2',
#     'social_core.backends.facebook.FacebookOAuth2',

#     'django.contrib.auth.backends.ModelBackend',
# )


# Option for PostgreSQL to store the extracted extra_data
# SOCIAL_AUTH_POSTGRES_JSONFIELD = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Created Apps
    'auth.apps.AuthConfig',
    'Contact.apps.ContactConfig',
    'chat.apps.ChatConfig',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BigChat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BigChat.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
