# Generated by Django 2.1.1 on 2018-10-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='chat_list_id',
            field=models.TextField(blank=True),
        ),
    ]
