# Generated by Django 2.1.2 on 2018-10-21 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0002_auto_20181021_2242'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
