# Generated by Django 2.1.2 on 2018-11-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0002_auto_20181120_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
