# Generated by Django 2.1.1 on 2018-10-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0002_users_chat_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='chat_list_id',
            field=models.TextField(default=''),
        ),
    ]
