# Generated by Django 2.1.2 on 2018-10-20 21:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0002_remove_users_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='chat_list_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, unique=True), null=True, size=None),
        ),
    ]
