# Generated by Django 2.1.2 on 2018-10-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0003_auto_20181021_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='chat_list_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
