# Generated by Django 2.1.1 on 2018-10-22 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0003_auto_20181021_1631'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='User',
        ),
    ]
