# Generated by Django 2.1.1 on 2018-10-22 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0004_auto_20181021_1729'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
