# Generated by Django 2.1.2 on 2018-10-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0004_auto_20181021_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='chat_list_id',
            field=models.TextField(blank=True),
        ),
    ]
