# Generated by Django 2.1.1 on 2018-10-22 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0005_auto_20181021_1730'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='myAuth_users',
        ),
    ]
