# Generated by Django 2.1.2 on 2018-11-01 19:34

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('friend_requests_emails_sent', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()]), size=None)),
                ('friend_requests_emails_recieved', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()]), size=None)),
            ],
            options={
                'db_table': 'friend_requests',
            },
        ),
    ]
