# Generated by Django 2.1.2 on 2018-11-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addFriends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmember',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
